version: '3'

services:
  db:
    image: mariadb:latest
    container_name: nextcloud-db
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_PASSWORD: examplepassword
      MYSQL_USER: nextclouduser
      MYSQL_DATABASE: nextcloud
    volumes:
      - /mnt/nextcloud:/var/lib/mysql
    networks:
      - nextcloud-network

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    environment:
      MYSQL_PASSWORD: examplepassword
      MYSQL_USER: nextclouduser
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
    ports:
      - "80:80"
    volumes:
      - /mnt/nextcloud/data:/var/www/html
    networks:
      - nextcloud-network
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - nextcloud-network
    ports:
      - "80:80"
    restart: always
    volumes:
      - /gitea-server/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  nextcloud-db-data:
    driver: local
  nextcloud-data:
    driver: local

networks:
  nextcloud-network:
    driver: bridge
